### ISSUE TITLE
How to use helm-dashboard to manage multiple different nodes

### ISSUE THREAD

**Issue by 2432234085** [komodorio/helm-dashboard#205]
### Description

When I installed the UI, there is no option to import other clusters

### Screenshots

![image](https://user-images.githubusercontent.com/87967906/215374986-6aac1a2a-5b2c-43e4-bff6-6704c71c3ae4.png)

**Comment by undera** [comment]
Helm dashboard reads the content of your kubectl config and takes cluster connection information from there. This usually how it works when installed locally. 

There is an [official doc](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) about managing the kubeconfig, but usually people have that config updated by some cloud provider toolkit or other script. For instance, when I create my Kind cluster, it adds itself into config automatically. Same happens when I authenticate to cloud cluster with GKE CLI tool.

Note that when installed into cluster, there is no kubectl config around, and it works only for that specific cluster.
