### ISSUE TITLE
Error: unknown flag: --time-format

### ISSUE THREAD

**Issue by enriqueayala** [komodorio/helm-dashboard#36]
Error received from tabs:  "Installed" and "Repository"  
<img width="729" alt="2022-10-24 16_35_04-Helm Dashboard and 1 more page - Work - Microsoft​ Edge" src="https://user-images.githubusercontent.com/10963531/197634231-d337c208-7a60-4e0d-8ea4-5c971eadcc01.png">

helm-dashboard version v0.2.0
helm version "v3.2.1"

**Comment by undera** [comment]
Looks like your version of Helm is a bit old and misses the support for `--time-format` flag. This option exists since Helm version 3.4.0: https://github.com/helm/helm/commit/c5e9732a9fdda5c1bb74a1d29827cf60158d218c, which is from late 2020.
Please consider upgrading your Helm installation. I will add to docs the minimal version requirement.

**Comment by enriqueayala** [comment]
thanks ! docs update should definitely help
