### ISSUE TITLE
Error when installing : Illegal option -

### ISSUE THREAD

**Issue by DevLazio** [komodorio/helm-dashboard#40]
Hello,
when I try to install or update the plugin I encounter the following error:
```bash
/bin/sh: 0: Illegal option -
Error: plugin install hook for "dashboard" exited with error
```

![image](https://user-images.githubusercontent.com/2280811/197715808-b8ba0334-f8ea-4e63-a588-3e95b976ad19.png)

Using GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) on WSL2 (Ubuntu 22.04.1 LTS)

If I try to use `helm dashboard` anyway I get 
```bash
Error: fork/exec /home/vmariette/.local/share/helm/plugins/helm-dashboard.git/bin/helm-dashboard: no such file or directory
```

**Comment by undera** [comment]
This looks very unusual, since it's a basic shell script inside. However, there is a workaround for you: you can just download the appropriate [release package](https://github.com/komodorio/helm-dashboard/releases) for your platform, unpack it and just run `dashboard` binary from it. The result will be exactly the same as you would run `helm dashboard`.

**Comment by undera** [comment]
No more feedback received...
